Meteor.subscribe('allPiece');
Meteor.subscribe('allImageClons');
Meteor.subscribe('allImages');
Meteor.subscribe('allRegistered');
Meteor.subscribe('allLandingTexts');
Meteor.subscribe('allAdmins');
Meteor.subscribe('allUsers');
Meteor.subscribe('allUserRole');
Meteor.subscribe('allUser2Role');